version: '3.8'
services:
  db:
    # Configuración de la base de datos PostgreSQL
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    # Configuración del servicio de la API en Python
    image: python
    command: >
      sh -c "
      pip install --upgrade pip && 
      pip install -r /app/requirements.txt 
      && python /app/app.py"
    networks:
      - postgres
      - api_network
    depends_on:
      - db
    ports:
      - "8000:5000"
    volumes:
      - ./api:/app

  centos:
    # Configuración de CentOS con ajustes específicos
    image: centos
    command: >
      bash -c "
      sed -i -e 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* &&
      sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&
      yum install -y gcc make postgresql-devel python3-devel &&
      yum install -y python3 python3-pip &&
      pip3 install psycopg2-binary &&
      python3 /usr/local/bin/load.py"
    networks:
      - postgres
      - centos_network
    volumes:
      - /Users/dd/docker/xaltestde/centos/data:/tmp
      - /Users/dd/docker/xaltestde/centos/scripts:/usr/local/bin

  airflow-init:
    image: apache/airflow:latest
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:example@db/postgres
    command: >
      bash -c "airflow db migrate &&
      airflow users create --role Admin --username admin --email dd_gr@outlook.com --firstname daniel --lastname gonzalez --password admin123"
    depends_on:
      db:
         condition: service_healthy
    networks:
      - postgres

  airflow-webserver:
    image: apache/airflow:latest
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:example@db/postgres
      - AIRFLOW__CORE__FERNET_KEY=GMWUu3EMD1fI9mXztzP91bWQSXJoqmnQIiPPtNeFhF0=
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key
      - AIRFLOW__WEBSERVER__RBAC=True
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: airflow webserver
    networks:
      - postgres
      - centos_network

  airflow-scheduler:
    image: apache/airflow:latest
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:example@db/postgres
      - AIRFLOW__CORE__FERNET_KEY=GMWUu3EMD1fI9mXztzP91bWQSXJoqmnQIiPPtNeFhF0=
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: airflow scheduler
    networks:
      - postgres
      - centos_network

networks:
  postgres:
    driver: bridge

  api_network:
    driver: bridge

  centos_network:
    driver: bridge
